DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS idea;
DROP TABLE IF EXISTS project;

CREATE TABLE user (
	id	INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL,
	img_link TEXT,
	description TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	projectname TEXT NOT NULL,
	description TEXT,
	user_fk INTEGER NOT NULL,
	FOREIGN KEY (user_fk) REFERENCES user (id)
);

CREATE TABLE idea (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	kind TEXT NOT NULL,
	project_fk INTEGER NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	tags TEXT,
	comments TEXT,
	FOREIGN KEY (project_fk) REFERENCES project (id)
);

